import React, { useState } from 'react';
import { Card, Table, Menu, Row, Col, Tag, Input, message, Button, Upload, Select, DatePicker } from 'antd';
import { EyeOutlined, DeleteOutlined, CloudUploadOutlined, MailOutlined, PlusOutlined, PushpinOutlined, FileExcelOutlined, CopyOutlined, EditOutlined, LinkOutlined } from '@ant-design/icons';
// import { Card, Table,  Badge, Menu, Tag,Modal } from 'antd';
import { useNavigate } from 'react-router-dom';
import 'react-quill/dist/quill.snow.css';
import { UploadOutlined } from "@ant-design/icons";
import ReactQuill from 'react-quill';
import OrderListData from 'assets/data/order-list.data.json';
import Flex from 'components/shared-components/Flex'
import utils from 'utils';
import AvatarStatus from 'components/shared-components/AvatarStatus';
import userData from 'assets/data/user-list.data.json';
import dayjs from 'dayjs';
import EllipsisDropdown from 'components/shared-components/EllipsisDropdown';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';

const { Option } = Select;

const AddInvoice = () => {
    const [users, setUsers] = useState(userData);
    // const [selectedRowKeys, setSelectedRowKeys] = useState([]);
    // const [list, setList] = useState(OrderListData);
    const [isExpanded, setIsExpanded] = useState(false);

    const [discountType, setDiscountType] = useState("%");
    const [discountValue, setDiscountValue] = useState(0);

    const [rows, setRows] = useState([
        {
            id: Date.now(),
            item: "",
            quantity: "",
            price: "",
            discount: "",
            tax: "",
            amount: "0",
            description: "",
            isNew: false,
        },
    ]);

    // Function to handle adding a new row
    const handleAddRow = () => {
        setRows([
            ...rows,
            {
                id: Date.now(),
                item: "",
                quantity: "",
                price: "",
                discount: "",
                tax: "",
                amount: "0",
                description: "",
                isNew: true,
            },
        ]);
    };

    // Function to handle deleting a row
    const handleDeleteRow = (id) => {
        const updatedRows = rows.filter((row) => row.id !== id);
        setRows(updatedRows);
        alert("Are you sure you want to delete this element?")
        // calculateTotals(updatedRows);
    };
    const navigate = useNavigate();

    const onSubmit = (values) => {
        console.log('Submitted values:', values);
        message.success('Job added successfully!');
        navigate('/apps/sales/invoice/');
    };

    const initialValues = {
        invoiceNumber: '',
        invoiceDate: null,
        duedate: null,
        currency: '',
        exchangerate: '',
        client: '',
        project: '',
        tax: '',
        bankaccount: '',
        paymentdetails: '',
        shippingAddress: '',
        generatedBy: '',
    };

    const validationSchema = Yup.object({
        invoiceNumber: Yup.string().required('Please enter invoice number.'),
        invoiceDate: Yup.date().nullable().required('Invoice Date is required.'),
        duedate: Yup.date().nullable().required('Due Date is required.'),
        currency: Yup.string().required('Please select currency.'),
        exchangerate: Yup.string().required('Please enter exchange rate.'),
        client: Yup.string().required('Please enter client name.'),
        project: Yup.string().required('Please enter project name.'),
        tax: Yup.string().required('Please select tax.'),
        bankaccount: Yup.string().required('Please select bank account.'),
        paymentdetails: Yup.string().required('Please select payment details.'),
        shippingAddress: Yup.string().required('Please enter shipping address.'),
        generatedBy: Yup.string().required('Please select generated by.'),
    });


    // Search functionality
    // const onSearch = (e) => {
    //     const value = e.currentTarget.value;
    //     const searchArray = value ? list : OrderListData;
    //     const data = utils.wildCardSearch(searchArray, value);
    //     setList(data);
    //     setSelectedRowKeys([]);
    // };



    return (
        <>
            <div>
                <div className='bg-gray-50 ml-[-24px] mr-[-24px] mt-[-52px] mb-[-40px] rounded-t-lg rounded-b-lg p-4'>
                    <h2 className="mb-4 border-b pb-[30px] font-medium"></h2>
                    <Card className="border-0 mt-4">
                        <div className="">
                            <div className=" p-2">
                                <Formik
                                    initialValues={initialValues}
                                    validationSchema={validationSchema}
                                    onSubmit={onSubmit}
                                >
                                    {({ values, setFieldValue, handleSubmit, setFieldTouched }) => (
                                        <Form className="formik-form" onSubmit={handleSubmit}>
                                            <Row gutter={16}>
                                                <Col span={7}>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Invoice Number</label>
                                                        <div className='flex'>
                                                            <span className='border py-2 rounded-s-lg bg-[#f5f5f5] px-3'>INV#0</span>
                                                            <Field name="invoiceNumber" as={Input} placeholder="Enter Invoice Number" onBlur={() => setFieldTouched("invoiceNumber", true)} className=' rounded-e-lg rounded-s-none' />
                                                        </div>
                                                        <ErrorMessage name="invoiceNumber" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={4} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Invoice Date</label>
                                                        <DatePicker
                                                            className="w-full"
                                                            format="DD-MM-YYYY"
                                                            value={values.invoiceDate}
                                                            onChange={(invoiceDate) => setFieldValue('invoiceDate', invoiceDate)}
                                                            onBlur={() => setFieldTouched("invoiceDate", true)}
                                                        />
                                                        <ErrorMessage name="invoiceDate" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={4} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Due Date</label>
                                                        <DatePicker
                                                            className="w-full"
                                                            format="DD-MM-YYYY"
                                                            value={values.duedate}
                                                            onChange={(duedate) => setFieldValue('duedate', duedate)}
                                                            onBlur={() => setFieldTouched("duedate", true)}
                                                        />
                                                        <ErrorMessage name="duedate" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={5} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Currency</label>
                                                        <Field name="currency">
                                                            {({ field }) => (
                                                                <Select
                                                                    {...field}
                                                                    className="w-full"
                                                                    placeholder="Select Currency"
                                                                    onChange={(value) => setFieldValue('currency', value)}
                                                                    value={values.currency}
                                                                    onBlur={() => setFieldTouched("currency", true)}
                                                                >
                                                                    <Option value="usd$">USD($)</Option>
                                                                    <Option value="inr">INR(₹)</Option>
                                                                </Select>
                                                            )}
                                                        </Field>
                                                        <ErrorMessage name="currency" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>

                                                <Col span={4} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Exchange Rate</label>
                                                        <Field name="exchangerate" as={Input} placeholder="Enter Exchange Rate" />
                                                        <h6>( GBP To USD )</h6>
                                                        <ErrorMessage name="exchangerate" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Client</label>
                                                        <Field name="client" as={Input} placeholder="Enter Client Name" />
                                                        <ErrorMessage name="client" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Project</label>
                                                        <Field name="project" as={Input} placeholder="Website Copier Project" />
                                                        <ErrorMessage name="project" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Calculate Tax</label>
                                                        <Field name="tax">
                                                            {({ field }) => (
                                                                <Select
                                                                    {...field}
                                                                    className="w-full"
                                                                    placeholder="Select Tax"
                                                                    onChange={(value) => setFieldValue('tax', value)}
                                                                    value={values.tax}
                                                                    onBlur={() => setFieldTouched("tax", true)}
                                                                >
                                                                    <Option value="after">After Discount</Option>
                                                                    <Option value="before">Before Discount</Option>
                                                                </Select>
                                                            )}
                                                        </Field>
                                                        <ErrorMessage name="tax" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col>
                                                {/* <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Bank Account</label>
                                                        <Field name="tax">
                                                            {({ field }) => (
                                                                <Select
                                                                    {...field}
                                                                    className="w-full"
                                                                    placeholder="Select Bank Account"
                                                                    onChange={(value) => setFieldValue('bankaccount', value)}
                                                                    value={values.bankaccount}
                                                                    onBlur={() => setFieldTouched("bankaccount", true)}
                                                                >
                                                                    <Option value="xyz">XYZ</Option>
                                                                    <Option value="abc">abc</Option>
                                                                </Select>
                                                            )}
                                                        </Field>
                                                        <ErrorMessage name="bankaccount" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col> */}
                                                {/* <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Payment Details</label>
                                                        <Field name="tax">
                                                            {({ field }) => (
                                                                <Select
                                                                    {...field}
                                                                    className="w-full"
                                                                    placeholder="Select Payment Details"
                                                                    onChange={(value) => setFieldValue('paymentdetails', value)}
                                                                    value={values.paymentdetails}
                                                                    onBlur={() => setFieldTouched("paymentdetails", true)}
                                                                >
                                                                    <Option value="usd$">USD($)</Option>
                                                                    <Option value="inr">INR(₹)</Option>
                                                                </Select>
                                                            )}
                                                        </Field>
                                                        <ErrorMessage name="paymentdetails" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col> */}

                                                {/* <Col span={8} className='mt-2 hidden md:block lg:block'>

                                                </Col> */}

                                                {/* <Col span={8} className='mt-4'>
                                                    <div className="form-item">
                                                        <h1>Billing Address</h1>
                                                        <h6 className='text-sm mt-2'>961 Virginie Summit
                                                            Pollichstad, CA 75654</h6>

                                                    </div>
                                                </Col> */}
                                                {/* <Col span={8} className='mt-4'>
                                                    <div className="flex items-center w-full">
                                                        <label className='font-semibold mb-2'>Shipping Address</label>
                                                        <button
                                                            className="flex items-center cursor-pointer"
                                                            onClick={() => setIsExpanded(!isExpanded)}
                                                        >
                                                            <div className="text-base font-medium text-blue-500 flex items-center gap-2">
                                                                <PlusCircleOutlined />
                                                               Add Shipping Address
                                                            </div>
                                                        </button>
                                                    </div>

                                                   
                                                    {isExpanded && (
                                                        <div className="mt-4 w-full">
                                                                <div className="flex gap-6">
                                                                    <div>
                                                                        <img
                                                                            src="https://demo-saas.worksuite.biz/img/gravatar.png"
                                                                            alt="User"
                                                                            className="w-8 h-8 rounded-sm"
                                                                        />
                                                                    </div>
                                                                    <div className="flex-1">
                                                                        <ReactQuill placeholder="Enter Shipping Address" 
                                                                        onChange={(value) => setFieldValue('shippingAddress', value)}className="mt-2 w-full" />
                                                                         <ErrorMessage name="shippingAddress" component="div" className="error-message text-red-500 my-1" />
                                                                    </div>
                                                                </div>
                                                        </div>
                                                    )}
                                                </Col>
                                                {/* <Col span={8} className='mt-4'>
                                                    <div className="form-item">
                                                        <label className='font-semibold'>Shipping Address</label>
                                                        <ReactQuill
                                                            value={values.shippingAddress}
                                                            onChange={(value) => setFieldValue('shippingAddress', value)}
                                                            placeholder="Enter Shipping Address"
                                                        />
                                                        <ErrorMessage name="shippingAddress" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col> */}
                                                {/* <Col span={8} className='mt-2'>
                                                    <div className="form-item">
                                                        <label className='font-semibold mb-2'>Generated By</label>
                                                        <Field name="tax">
                                                            {({ field }) => (
                                                                <Select
                                                                    {...field}
                                                                    className="w-full"
                                                                    placeholder="Select Generated By"
                                                                    onChange={(value) => setFieldValue('generatedBy', value)}
                                                                    value={values.generatedBy}
                                                                    onBlur={() => setFieldTouched("generatedBy", true)}
                                                                >
                                                                    <Option value="WorkSuite">WorkSuite</Option>
                                                                </Select>
                                                            )}
                                                        </Field>
                                                        <ErrorMessage name="generatedBy" component="div" className="error-message text-red-500 my-1" />
                                                    </div>
                                                </Col> */}
                                            </Row>
                                        </Form>
                                    )}
                                </Formik>
                            </div>
                        </div>
                    </Card>

                    {/* <Col span={24}>
                        <h4 className='ms-4 font-semibold text-lg mb-3'>Product & Services</h4>
                    </Col> */}

                    <Card>
                        <div>
                            <div className="overflow-x-auto">

                                <table className="w-full border border-gray-200 bg-white">
                                    <thead className="bg-gray-100">
                                        <tr>
                                            <th className="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b">
                                                Description<span className="text-red-500">*</span>
                                            </th>
                                            <th className="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b">
                                                Quantity<span className="text-red-500">*</span>
                                            </th>
                                            <th className="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b">
                                                Unit Price <span className="text-red-500">*</span>
                                            </th>
                                            <th className="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b">
                                                TAX (%)
                                            </th>
                                            <th className="px-4 py-2 text-left text-sm font-medium text-gray-700 border-b">
                                                Amount<span className="text-red-500">*</span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {rows.map((row, index) => (
                                            <React.Fragment key={row.id}>
                                                <tr>
                                                    <td className="px-4 py-2 border-b">
                                                        <input
                                                            type="text"
                                                            placeholder="Item Name"
                                                            className="w-full p-2 border rounded-s"
                                                        />
                                                    </td>
                                                    <td className="px-4 py-2 border-b">
                                                        <input
                                                            type="text"
                                                            placeholder="Qty"
                                                            className="w-full p-2 border rounded"
                                                        />
                                                    </td>
                                                    <td className="px-4 py-2 border-b">
                                                        <div className="flex items-center">
                                                            <input
                                                                type="text"
                                                                placeholder="Price"
                                                                className="w-full p-2 border rounded-s"
                                                            />

                                                        </div>
                                                    </td>
                                                    <td className="px-4 py-2 border-b">
                                                        <div className="flex items-center">
                                                            <select className="w-full p-2 border rounded">
                                                                <option value="">Nothing Selected</option>
                                                                <option value="">GST:10%</option>
                                                                <option value="item1">CGST:18%</option>
                                                                <option value="item2">VAT:10%</option>
                                                                <option value="item1">IGST:10%</option>
                                                                <option value="item1">UTGST:10%</option>
                                                            </select>
                                                        </div>
                                                    </td>
                                                    <td className="px-4 py-2 border-b">
                                                        <span>0</span>
                                                        {/* <input
                                                    type="text"
                                                    placeholder="Tax (%)"
                                                    className="w-full p-2 border rounded"
                                                /> */}
                                                    </td>
                                                    {/* <td className="px-4 py-2 border-b text-center">0</td> */}
                                                    <td className="px-2 py-1 border-b text-center">
                                                        {row.isNew && (
                                                            <Button
                                                                danger
                                                                onClick={() => handleDeleteRow(row.id)}
                                                            >
                                                                <DeleteOutlined />
                                                            </Button>
                                                        )}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colSpan={4} className="px-4 py-2 border-b">
                                                        <textarea
                                                            rows={1}
                                                            placeholder="Description"
                                                            className="w-[70%] p-2 border rounded"
                                                        ></textarea>
                                                    </td>
                                                    <td colSpan={3} className="px-4 py-2 border-2 text-gray-300">
                                                        <Upload
                                                            action="http://localhost:5500/api/users/upload-cv"
                                                            listType="picture"
                                                            accept=".pdf"
                                                            maxCount={1}
                                                            showUploadList={{ showRemoveIcon: true }}
                                                        >
                                                            <div className="flex flex-col items-center">
                                                                <CloudUploadOutlined className='text-4xl text-blue-500' />
                                                                <span className="text-gray-600">Choose File</span>
                                                            </div>

                                                        </Upload>
                                                    </td>
                                                    {/* <td className='hidden'>
                                                        <span>0</span>
                                                    </td> */}
                                                </tr>
                                            </React.Fragment>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                            <div className="form-buttons text-left mt-2">
                                <Button className='border-0 text-blue-500' onClick={handleAddRow}>
                                    <PlusOutlined />  Add Items
                                </Button>
                            </div>

                            {/* Summary Section */}
                            <div className="mt-3 flex flex-col justify-end items-end space-y-2">
                                <table className='w-full lg:w-[50%] p-2'>
                                    {/* Sub Total */}
                                    <tr className="flex justify-between px-2  py-2 border-2">
                                        <td className="font-medium ">Sub Total</td>
                                        <td className="font-medium px-4 py-2">0.00</td>
                                    </tr>

                                    {/* Discount */}
                                    <tr className="flex px-2 justify-between items-center py-2 border-x-2 border-b-2">
                                        <td className="font-medium">Discount</td>
                                        <td className='flex items-center space-x-2'>
                                            <input
                                                type="number"
                                                value={discountValue}
                                                onChange={(e) => setDiscountValue(e.target.value)}
                                                className="w-16 p-1 border focus:outline-none focus:ring"
                                            />
                                            <select
                                                value={discountType}
                                                onChange={(e) => setDiscountType(e.target.value)}
                                                className="p-1 border focus:outline-none focus:ring"
                                            >
                                                <option value="%">%</option>
                                                <option value="$">Amount</option>
                                            </select>   
                                        </td>
                                        <td className="font-medium px-4 py-2">0.00</td>
                                    </tr>

                                    {/* Tax */}
                                    <tr className="flex justify-between px-2 py-2 border-b border-x-2">
                                        <td className="font-medium">Tax</td>
                                        <td className="font-medium">0.00</td>
                                    </tr>

                                    {/* Total */}
                                    <tr className="flex justify-between px-2 py-4 border-b bg-gray-100">
                                        <td className="font-bold text-lg">Total</td>
                                        <td className="font-bold text-lg">0.00</td>
                                    </tr>

                                    {/* Terms and Conditions */}
                                </table>
                            </div>
                            <div className="pt-4 text-right">
                                <h3 className="font-medium">Terms and Conditions</h3>
                                <p className="text-sm text-gray-600">Thank you for your business.</p>
                            </div>
                            <div className='mt-4'>
                                <span className='block mb-2'>Add File</span>
                                <Col span={24} >
                                    <Upload
                                        action="http://localhost:5500/api/users/upload-cv"
                                        listType="picture"
                                        accept=".pdf"
                                        maxCount={1}
                                        showUploadList={{ showRemoveIcon: true }}
                                        className='border-2 flex justify-center items-center p-10'

                                    >
                                        <span className='text-xl'>Choose File</span>
                                        {/* <CloudUploadOutlined className='text-4xl' /> */}
                                    </Upload>
                                </Col>
                            </div>
                        </div>
                    </Card>

                    <div className="form-buttons text-right">
                        <Button type="default" className="mr-2" onClick={() => navigate('/apps/sales/estimates')}>Cancel</Button>
                        <Button type="primary" htmlType="submit">Create</Button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default AddInvoice;

